# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-transcription-adapter-interface',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-transcription-adapter-interface',
                'lib_path': 'cjm_transcription_adapter_interface'},
  'syms': {}}
