"""The typed transcription task contract — `TranscriptionAdapter` ABC +
the provisional tool protocol (capability-unit Option C, pass-2 Thread 3).

Docs: https://cj-mills.github.io/cjm-transcription-adapter-interfaceadapter.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/adapter.ipynb.

# %% auto #0
__all__ = ['TranscriptionToolProtocol', 'TranscriptionAdapter']

# %% ../nbs/adapter.ipynb #b2f359ce
from abc import abstractmethod
from pathlib import Path
from typing import Any, ClassVar, Protocol, Union, runtime_checkable

from cjm_plugin_system.core.adapter import TaskAdapter

from .core import TranscriptionResult

# %% ../nbs/adapter.ipynb #101403e6
@runtime_checkable
class TranscriptionToolProtocol(Protocol):
    """PROVISIONAL structural contract for transcription-capable tools.

    Mirrors the fused-era surface (task-shaped `execute`); re-derived from
    native tool surfaces when the Option C cascade splits tools (stage 8).
    """
    def execute(self, audio: Union[str, Path], **kwargs) -> Any: ...


# %% ../nbs/adapter.ipynb #1671e992
class TranscriptionAdapter(TaskAdapter):
    """Typed transcription task adapter: model-ready audio in,
    `TranscriptionResult` out.

    Input contract (carried over from the fused-era TranscriptionPlugin):
    the caller guarantees MODEL-READY audio — format / sample-rate /
    channel handling happens upstream (ffmpeg `convert_for_model`), never
    in the adapter.

    Persistence sits BESIDE the task method (pass-2 Thread 3): the storage
    module's `TranscriptionStorage` provides the adapter-level cache /
    persist seam (`get_cached(audio_path, audio_hash, config_hash)` +
    `save_with_logging(...)`).

    The result DTO is wire-registered ("transcription.result"): returned
    values cross the worker boundary typed via the substrate's `core.wire`
    envelope.
    """

    task_name: ClassVar[str] = "transcription"
    required_tool_protocol: ClassVar[type] = TranscriptionToolProtocol  # PROVISIONAL

    @abstractmethod
    def transcribe(
        self,
        audio: Union[str, Path],  # Path to MODEL-READY audio (converted upstream)
        **kwargs,                 # Adapter-specific options (language, task, ...)
    ) -> TranscriptionResult:     # Typed transcription output
        """Transcribe model-ready audio to text."""
        ...

