"""Standardized result DTO for the transcription task — wire-registered
so results cross the worker boundary typed.

Docs: https://cj-mills.github.io/cjm-transcription-adapter-interfacecore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = ['TranscriptionResult']

# %% ../nbs/core.ipynb #5b7c288a
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from cjm_plugin_system.core.wire import wire_type

# %% ../nbs/core.ipynb #b7571f24
@wire_type("transcription.result")
@dataclass
class TranscriptionResult:
    """Standardized output for all transcription plugins."""
    text: str                                        # The transcribed text
    confidence: Optional[float] = None               # Overall confidence (0.0 to 1.0)
    segments: Optional[List[Dict[str, Any]]] = None  # Timestamped segments
    metadata: Dict[str, Any] = field(default_factory=dict)  # Additional metadata
