"""REMOVE-AFTER-OVERHAUL(option-c-cascade): class-identical legacy import surface; `TranscriptionResult` relocated to `cjm_capability_primitives.transcription` at execution stage 8 (Option C / PILLAR 1c — pure-compute tool capabilities depend on the data noun, never the adapter machinery).

Docs: https://cj-mills.github.io/cjm-transcription-adapter-interfacecore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/core.ipynb #5b7c288a
# REMOVE-AFTER-OVERHAUL(option-c-cascade): re-export shim; the class lives in
# cjm_capability_primitives.transcription (born-final home, relocated stage 8).
from cjm_capability_primitives.transcription import TranscriptionResult

__all__ = ["TranscriptionResult"]
