"""The generic (tool-agnostic) transcription adapter — cache-check, invoke the bound tool's pure-compute `transcribe`, persist. Reused across every tool capability satisfying `TranscriptionToolProtocol` (whisper, voxtral, ...), exactly as `GenericGraphStorageAdapter` is reused across graph backends.

Docs: https://cj-mills.github.io/cjm-transcription-adapter-interfacegeneric.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/generic.ipynb.

# %% auto #0
__all__ = ['GenericTranscriptionAdapter']

# %% ../nbs/generic.ipynb #gta-imports
import os
from pathlib import Path
from typing import Any, Union
from uuid import uuid4

from cjm_substrate.core.wire import get_call_envelope
from cjm_substrate.utils.hashing import hash_file, hash_bytes, hash_dict_canonical

from cjm_capability_primitives.transcription import TranscriptionResult
from .adapter import TranscriptionAdapter
from .storage import TranscriptionStorage

# %% ../nbs/generic.ipynb #gta-class
class GenericTranscriptionAdapter(TranscriptionAdapter):
    """Generic transcription adapter: cache-check -> pure-compute tool -> persist.

    Works against ANY tool satisfying `TranscriptionToolProtocol`. The bookends:

      1. cache check (audio_path + audio_hash + config_hash) BEFORE invoking the
         tool, so a hit never loads the model;
      2. the tool's pure-compute `transcribe` on a miss / forced call;
      3. `save_with_logging` (upsert by audio_path + config_hash).

    `config_hash` reuses `hash_dict_canonical(get_current_config())` — the SAME
    canonical hash the fused-era plugins used — so a migrated tool keeps hitting
    rows written before the split. `force` rides `CallEnvelope.control` (not a
    task kwarg, keeping `transcribe(audio)` pure). Storage lives at
    `<CAPABILITY_DATA_DIR>/transcriptions.db`; the substrate injects the
    per-capability `CAPABILITY_DATA_DIR` at spawn (it owns the data-dir convention),
    so the adapter neither hard-codes a path nor asks the tool for one.
    """

    def _get_storage(self) -> TranscriptionStorage:
        """Lazily open the per-capability cache DB under the substrate-injected
        CAPABILITY_DATA_DIR (created at worker spawn)."""
        if getattr(self, "_storage", None) is None:
            db_path = os.path.join(os.environ["CAPABILITY_DATA_DIR"], "transcriptions.db")
            self._storage = TranscriptionStorage(db_path)
        return self._storage

    def transcribe(
        self,
        audio: Union[str, Path],  # Path to MODEL-READY audio (converted upstream)
        **kwargs,                 # Provenance (job_id / source_*_time) + tool options
    ) -> TranscriptionResult:     # Typed transcription output
        """Cache-check, invoke the bound tool's pure-compute `transcribe`, persist."""
        audio_path = str(audio)
        audio_hash = hash_file(audio_path)
        config_hash = hash_dict_canonical(self.tool.get_current_config())

        env = get_call_envelope()
        force = bool(env.control.get("force")) if env is not None else False

        storage = self._get_storage()
        if not force:
            cached = storage.get_cached(audio_path, audio_hash, config_hash)
            if cached is not None:
                return TranscriptionResult(
                    text=cached.text, confidence=None,
                    segments=cached.segments, metadata=cached.metadata,
                )

        # Pure compute on the tool (cache miss / forced).
        result = self.tool.transcribe(audio, **kwargs)

        # Persist. job_id rides the provenance kwarg channel, falling back to the
        # envelope's queue job id, then a fresh uuid (the row id is write-only
        # provenance; the cache key does not include it).
        text_hash = hash_bytes(result.text.encode())
        job_id = kwargs.get("job_id") or (env.job_id if env is not None else None) or str(uuid4())
        storage.save_with_logging(
            job_id=job_id, audio_path=audio_path, audio_hash=audio_hash,
            config_hash=config_hash, text=result.text, text_hash=text_hash,
            segments=result.segments, metadata=result.metadata,
        )
        return result
